version: "3.8"

services:
  gobble-app:
    # build using the DockerFile in the the current directory
    build: .
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy-data:
  caddy-config:
